baseURL: https://tiagojct.eu/liber-oceani/
locale: pt-PT
title: Liber Oceani
enableEmoji: false
enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true
      hardWraps: true
    extensions:
      typographer:
        disable: true

permalinks:
  cantos: /cantos/:slug/

outputFormats:
  anotacoes:
    mediaType: application/json
    baseName: anotacoes
    isPlainText: true
    notAlternative: true

outputs:
  home: [HTML, RSS, anotacoes]

pagination:
  pagerSize: 200
